# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_deploy:
      - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: release
    env: dbplyr="devel"
    before_script: Rscript -e 'remotes::install_github("tidyverse/dbplyr")'
  - r: release
    env: BIGRQUERY_PASSWORD=''
  - r: oldrel
  - r: 3.3
  - r: 3.2
# - r: 3.1  # dbplyr fails on 3.1

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - BIGQUERY_TEST_PROJECT=bigrquery-examples
