# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
  - r: release
    env: dbplyr="devel"
    before_script: Rscript -e 'remotes::install_github("tidyverse/dbplyr")'
  - r: release
    env: BIGRQUERY_PASSWORD=''
  - r: oldrel
    env: BIGRQUERY_PASSWORD=''
  - r: 3.4
    env: BIGRQUERY_PASSWORD=''
  - r: 3.3
    env: BIGRQUERY_PASSWORD=''
  - r: 3.2
    env: BIGRQUERY_PASSWORD=''

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
