# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- oldrel
- release
- devel

before_install:
- test $encrypted_95be9bef5db7_key && openssl aes-256-cbc
    -K $encrypted_95be9bef5db7_key -iv $encrypted_95be9bef5db7_iv
    -in tests/testthat/service-token.json.enc -out ~/.bigrquery-token.json -d

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false
